In [ ]:
#       Data Importing, Merging, and Cleaning

In [1]:
import pandas as pd 
internet_sales=pd.read_excel("InternetSales.xlsx")
products=pd.read_csv("Products.csv")
customers=pd.read_json("customers.json")
sales_territory=pd.read_parquet("SalesTerritory.parquet",engine="fastparquet")

In [2]:
internet_sales.head()

,ProductKey,OrderDate,ShipDate,CustomerKey,PromotionKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,RevisionNumber,OrderQuantity,...,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,29,6,98,19,36,100
0,310,2010-12-29,2011-01-05,21768,1,6,SO43697,1,1,1,...,0,0,2171.2942,2171.2942,NaN,NaN,NaN,3578.27,NaN,NaN
1,346,2010-12-29,2011-01-05,28389,1,7,SO43698,1,1,1,...,0,0,1912.1544,1912.1544,NaN,NaN,NaN,NaN,NaN,NaN
2,346,2010-12-29,2011-01-05,25863,1,1,SO43699,1,1,1,...,0,0,1912.1544,1912.1544,NaN,NaN,NaN,NaN,NaN,3399.9900
3,336,2010-12-29,2011-01-05,14501,1,4,SO43700,1,1,1,...,0,0,413.1463,413.1463,NaN,NaN,NaN,NaN,NaN,699.0982
4,346,2010-12-29,2011-01-05,11003,1,9,SO43701,1,1,1,...,0,0,1912.1544,1912.1544,NaN,3399.99,NaN,NaN,NaN,NaN

In [3]:
products.head()

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,NaN,NaN,Adjustable Race,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
1,2,BA-8327,NaN,NaN,NaN,Bearing Ball,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
2,3,BE-2349,NaN,NaN,NaN,BB Ball Bearing,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
3,4,BE-2908,NaN,NaN,NaN,Headset Ball Bearings,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
4,5,BL-2036,NaN,NaN,NaN,Blade,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current

In [4]:
customers.head()

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,12725,171,AW00012725,NaN,Gabrielle,NaN,James,0,1916-02-10,M,...,Manual,Obrero,Ouvrier,0,2,Nonnendamm 6500,NaN,1 (11) 500 555-0125,2013-08-18,1-2 Miles
1,16455,208,AW00016455,NaN,Deb,A,Moreno,0,1917-02-09,M,...,Manual,Obrero,Ouvrier,0,2,"99, rue du Départ",NaN,1 (11) 500 555-0144,2013-03-27,0-1 Miles
2,14841,171,AW00014841,NaN,Franklin,NaN,Pal,0,1917-06-05,M,...,Manual,Obrero,Ouvrier,1,1,Wertheimer Straße 8,NaN,1 (11) 500 555-0185,2013-09-02,1-2 Miles
3,18034,160,AW00018034,NaN,Ethan,J,Robinson,0,1917-09-20,M,...,Manual,Obrero,Ouvrier,0,2,Celler Weg 5,NaN,1 (11) 500 555-0160,2013-05-21,0-1 Miles
4,14992,228,AW00014992,NaN,Dale,B,Andersen,0,1918-02-11,M,...,Manual,Obrero,Ouvrier,1,1,2844 Plymouth Drive,NaN,1 (11) 500 555-0182,2013-09-04,5-10 Miles

In [5]:
sales_territory.head()

,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,1,1,Northwest,United States,North America
1,2,2,Northeast,United States,North America
2,3,3,Central,United States,North America
3,4,4,Southwest,United States,North America
4,5,5,Southeast,United States,North America

In [6]:
currency_columns=[29, 6, 98, 19, 36, 100]
id_columns=[i for i in internet_sales.columns if i not in currency_columns]
sales_melted=internet_sales.melt(id_vars=id_columns,value_vars=currency_columns,var_name="currencyKEY",value_name="SalesAmount")
sales_melted=sales_melted.dropna(subset="SalesAmount")
currency_dictionaire=currency_dict = {6: 'AUD',19: 'CAD',29: 'DEM',36: 'EUR',98: 'GBP',100: 'USD'}
sales_melted["currencyKEY"]=sales_melted["currencyKEY"].map(currency_dictionaire)
sales_melted

,ProductKey,OrderDate,ShipDate,CustomerKey,PromotionKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,RevisionNumber,OrderQuantity,UnitPrice,ExtendedAmount,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,currencyKEY,SalesAmount
15,311,2011-01-01,2011-01-08,13513,1,8,SO43712,1,1,1,3578.27,3578.27,0,0,2171.2942,2171.2942,DEM,3578.27
23,311,2011-01-03,2011-01-10,13264,1,8,SO43720,1,1,1,3578.27,3578.27,0,0,2171.2942,2171.2942,DEM,3578.27
28,311,2011-01-05,2011-01-12,13258,1,8,SO43725,1,1,1,3578.27,3578.27,0,0,2171.2942,2171.2942,DEM,3578.27
40,311,2011-01-08,2011-01-15,13261,1,8,SO43737,1,1,1,3578.27,3578.27,0,0,2171.2942,2171.2942,DEM,3578.27
55,311,2011-01-11,2011-01-18,13265,1,8,SO43752,1,1,1,3578.27,3578.27,0,0,2171.2942,2171.2942,DEM,3578.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362383,485,2014-01-28,2014-02-04,15868,1,6,SO75122,1,1,1,21.98,21.98,0,0,8.2205,8.2205,USD,21.98
362384,225,2014-01-28,2014-02-04,15868,1,6,SO75122,2,1,1,8.99,8.99,0,0,6.9223,6.9223,USD,8.99
362385,485,2014-01-28,2014-02-04,18759,1,6,SO75123,1,1,1,21.98,21.98,0,0,8.2205,8.2205,USD,21.98
362386,486,2014-01-28,2014-02-04,18759,1,6,SO75123,2,1,1,159.00,159.00,0,0,59.4660,59.4660,USD,159.00
362387,225,2014-01-28,2014-02-04,18759,1,6,SO75123,3,1,1,8.99,8.99,0,0,6.9223,6.9223,USD,8.99

In [7]:
Data_frame_finale=sales_melted.merge(customers,on="CustomerKey",how="left")
Data_frame_finale=Data_frame_finale.merge(products,on="ProductKey",how="left")
Data_frame_finale=Data_frame_finale.merge(sales_territory,on="SalesTerritoryKey",how="left")
Data_frame_finale

,ProductKey,OrderDate,ShipDate,CustomerKey,PromotionKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,RevisionNumber,OrderQuantity,...,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,311,2011-01-01,2011-01-08,13513,1,8,SO43712,1,1,1,...,Dieses Fahrrad wird von Rennprofis gefahren. E...,レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...,Bu bisiklet yarışçılar tarafından kullanılmakt...,2011-07-01,2007-12-28,NaN,8,Germany,Germany,Europe
1,311,2011-01-03,2011-01-10,13264,1,8,SO43720,1,1,1,...,Dieses Fahrrad wird von Rennprofis gefahren. E...,レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...,Bu bisiklet yarışçılar tarafından kullanılmakt...,2011-07-01,2007-12-28,NaN,8,Germany,Germany,Europe
2,311,2011-01-05,2011-01-12,13258,1,8,SO43725,1,1,1,...,Dieses Fahrrad wird von Rennprofis gefahren. E...,レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...,Bu bisiklet yarışçılar tarafından kullanılmakt...,2011-07-01,2007-12-28,NaN,8,Germany,Germany,Europe
3,311,2011-01-08,2011-01-15,13261,1,8,SO43737,1,1,1,...,Dieses Fahrrad wird von Rennprofis gefahren. E...,レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...,Bu bisiklet yarışçılar tarafından kullanılmakt...,2011-07-01,2007-12-28,NaN,8,Germany,Germany,Europe
4,311,2011-01-11,2011-01-18,13265,1,8,SO43752,1,1,1,...,Dieses Fahrrad wird von Rennprofis gefahren. E...,レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...,Bu bisiklet yarışçılar tarafından kullanılmakt...,2011-07-01,2007-12-28,NaN,8,Germany,Germany,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60334,485,2014-01-28,2014-02-04,15868,1,6,SO75122,1,1,1,...,Schutzbleche zum Aufstecken passen auf fast al...,クリップオン式フェンダーは、ほとんどのマウンテン バイクに適合します。,Klipsli çamurluklar çoğu dağ bisikletine uyar.,2013-07-01,NaN,Current,6,Canada,Canada,North America
60335,225,2014-01-28,2014-02-04,15868,1,6,SO75122,2,1,1,...,"Traditionelles Design mit Klapprand, Einheitsg...",跳ね上げ式のつばを持つトラディショナルなスタイルで、フリーサイズです。,"Klasik stil, herkese uygun tek bir boyda.",2013-07-01,NaN,Current,6,Canada,Canada,North America
60336,485,2014-01-28,2014-02-04,18759,1,6,SO75123,1,1,1,...,Schutzbleche zum Aufstecken passen auf fast al...,クリップオン式フェンダーは、ほとんどのマウンテン バイクに適合します。,Klipsli çamurluklar çoğu dağ bisikletine uyar.,2013-07-01,NaN,Current,6,Canada,Canada,North America
60337,486,2014-01-28,2014-02-04,18759,1,6,SO75123,2,1,1,...,Optimaler Allzweck-Fahrradständer für die Wart...,自宅での作業にも完璧な多目的スタンドで、迅速な調整が可能なクランプと鋼構造を備えています。,Evinizde bisikletiniz üzerinde çalışmanız için...,2013-07-01,NaN,Current,6,Canada,Canada,North America
60338,225,2014-01-28,2014-02-04,18759,1,6,SO75123,3,1,1,...,"Traditionelles Design mit Klapprand, Einheitsg...",跳ね上げ式のつばを持つトラディショナルなスタイルで、フリーサイズです。,"Klasik stil, herkese uygun tek bir boyda.",2013-07-01,NaN,Current,6,Canada,Canada,North America

In [8]:
Data_frame_finale.dtypes.to_string()

'ProductKey                             int64\nOrderDate                     datetime64[us]\nShipDate                      datetime64[us]\nCustomerKey                            int64\nPromotionKey                           int64\nSalesTerritoryKey                      int64\nSalesOrderNumber                         str\nSalesOrderLineNumber                   int64\nRevisionNumber                         int64\nOrderQuantity                          int64\nUnitPrice                            float64\nExtendedAmount                       float64\nUnitPriceDiscountPct                   int64\nDiscountAmount                         int64\nProductStandardCost                  float64\nTotalProductCost                     float64\ncurrencyKEY                              str\nSalesAmount                          float64\nGeographyKey                           int64\nCustomerAlternateKey                     str\nTitle                                    str\nFirstName                                str\nMiddleName                               str\nLastName                                 str\nNameStyle                              int64\nBirthDate                                str\nMaritalStatus                            str\nSuffix                                   str\nGender                                   str\nEmailAddress                             str\nYearlyIncome                           int64\nTotalChildren                          int64\nNumberChildrenAtHome                   int64\nEnglishEducation                         str\nSpanishEducation                         str\nFrenchEducation                          str\nEnglishOccupation                        str\nSpanishOccupation                        str\nFrenchOccupation                         str\nHouseOwnerFlag                         int64\nNumberCarsOwned                        int64\nAddressLine1                             str\nAddressLine2                             str\nPhone                                    str\nDateFirstPurchase                        str\nCommuteDistance                          str\nProductAlternateKey                      str\nProductSubcategoryKey                float64\nWeightUnitMeasureCode                    str\nSizeUnitMeasureCode                      str\nEnglishProductName                       str\nSpanishProductName                       str\nFrenchProductName                        str\nStandardCost                         float64\nFinishedGoodsFlag                      int64\nColor                                    str\nSafetyStockLevel                       int64\nReorderPoint                           int64\nListPrice                            float64\nSize                                     str\nSizeRange                                str\nWeight                               float64\nDaysToManufacture                      int64\nProductLine                              str\nDealerPrice                          float64\nClass                                    str\nStyle                                    str\nModelName                                str\nEnglishDescription                       str\nFrenchDescription                        str\nChineseDescription                       str\nArabicDescription                        str\nHebrewDescription                        str\nThaiDescription                          str\nGermanDescription                        str\nJapaneseDescription                      str\nTurkishDescription                       str\nStartDate                                str\nEndDate                                  str\nStatus                                   str\nSalesTerritoryAlternateKey             int64\nSalesTerritoryRegion                  object\nSalesTerritoryCountry                 object\nSalesTerritoryGroup                   object'

In [9]:
Data_frame_finale[["BirthDate", "DateFirstPurchase", "StartDate", "EndDate"]].head()

    BirthDate DateFirstPurchase   StartDate     EndDate
0  1947-03-08        2011-01-01  2011-07-01  2007-12-28
1  1961-11-20        2011-01-03  2011-07-01  2007-12-28
2  1962-08-31        2011-01-05  2011-07-01  2007-12-28
3  1962-10-03        2011-01-08  2011-07-01  2007-12-28
4  1961-07-21        2011-01-11  2011-07-01  2007-12-28

In [10]:
Data_frame_finale["BirthDate"]=pd.to_datetime(Data_frame_finale["BirthDate"])
Data_frame_finale["DateFirstPurchase"]=pd.to_datetime(Data_frame_finale["DateFirstPurchase"])
Data_frame_finale["StartDate"]=pd.to_datetime(Data_frame_finale["StartDate"])
Data_frame_finale["EndDate"]=pd.to_datetime(Data_frame_finale["EndDate"])

In [11]:
Data_frame_finale[["BirthDate", "DateFirstPurchase", "StartDate", "EndDate"]].dtypes

BirthDate            datetime64[us]
DateFirstPurchase    datetime64[us]
StartDate            datetime64[us]
EndDate              datetime64[us]
dtype: object

In [12]:
display(Data_frame_finale["ProductSubcategoryKey"].value_counts(dropna=False).sum())
Data_frame_finale["ProductSubcategoryKey"].apply(float.is_integer).all()

np.int64(60339)

np.True_

In [33]:
Data_frame_finale["ProductSubcategoryKey"]=Data_frame_finale["ProductSubcategoryKey"].astype(int)

In [34]:
Data_frame_finale.dtypes.to_string()

'ProductKey                             int64\nOrderDate                     datetime64[us]\nShipDate                      datetime64[us]\nCustomerKey                            int64\nPromotionKey                           int64\nSalesTerritoryKey                      int64\nSalesOrderNumber                         str\nSalesOrderLineNumber                   int64\nRevisionNumber                         int64\nOrderQuantity                          int64\nUnitPrice                            float64\nExtendedAmount                       float64\nUnitPriceDiscountPct                   int64\nDiscountAmount                         int64\nProductStandardCost                  float64\nTotalProductCost                     float64\ncurrencyKEY                              str\nSalesAmount                          float64\nGeographyKey                           int64\nCustomerAlternateKey                     str\nFirstName                                str\nMiddleName                               str\nLastName                                 str\nNameStyle                              int64\nBirthDate                     datetime64[us]\nMaritalStatus                            str\nGender                                   str\nEmailAddress                             str\nYearlyIncome                           int64\nTotalChildren                          int64\nNumberChildrenAtHome                   int64\nEnglishEducation                         str\nSpanishEducation                         str\nFrenchEducation                          str\nEnglishOccupation                        str\nSpanishOccupation                        str\nFrenchOccupation                         str\nHouseOwnerFlag                         int64\nNumberCarsOwned                        int64\nAddressLine1                             str\nPhone                                    str\nDateFirstPurchase             datetime64[us]\nCommuteDistance                          str\nProductAlternateKey                      str\nProductSubcategoryKey                  int64\nEnglishProductName                       str\nSpanishProductName                       str\nFrenchProductName                        str\nStandardCost                         float64\nFinishedGoodsFlag                      int64\nColor                                    str\nSafetyStockLevel                       int64\nReorderPoint                           int64\nListPrice                            float64\nDaysToManufacture                      int64\nProductLine                              str\nDealerPrice                          float64\nModelName                                str\nEnglishDescription                       str\nFrenchDescription                        str\nChineseDescription                       str\nArabicDescription                        str\nHebrewDescription                        str\nThaiDescription                          str\nGermanDescription                        str\nJapaneseDescription                      str\nTurkishDescription                       str\nStartDate                     datetime64[us]\nStatus                                   str\nSalesTerritoryAlternateKey             int64\nSalesTerritoryRegion                  object\nSalesTerritoryCountry                 object\nSalesTerritoryGroup                   object'

In [37]:
missing_values=Data_frame_finale.isna().sum()/len(Data_frame_finale)*100
display(missing_values[missing_values>50])

Series([], dtype: float64)

In [32]:
Data_frame_finale=Data_frame_finale.drop(columns=["Title","Suffix","AddressLine2","WeightUnitMeasureCode","SizeUnitMeasureCode","Size","SizeRange","Weight"

,"Class","Style","EndDate"],errors='ignore')

In [38]:
Data_frame_finale.shape

(60339, 73)

In [46]:
missing_values_2=Data_frame_finale.isna().sum()
display(missing_values_2[missing_values_2>0])

MiddleName            25471
SpanishProductName    13135
FrenchProductName     13135
Color                 28919
Status                 5369
dtype: int64

In [49]:
Data_frame_finale["SpanishProductName"]=Data_frame_finale["SpanishProductName"].fillna(Data_frame_finale["EnglishProductName"])
Data_frame_finale["FrenchProductName"]=Data_frame_finale["FrenchProductName"].fillna(Data_frame_finale["EnglishProductName"])

In [54]:
Data_frame_finale["MiddleName"] = Data_frame_finale["MiddleName"].fillna("  ")
Data_frame_finale["Color"] = Data_frame_finale["Color"].fillna("  ")
Data_frame_finale["Status"] = Data_frame_finale["Status"].fillna("Current")

In [59]:
Data_frame_finale.isna().sum().sum()

np.int64(0)

In [63]:
Data_frame_finale.duplicated().sum()

np.int64(0)

In [74]:
text_columns=Data_frame_finale.select_dtypes(include=['string','object']).columns
for i in text_columns:
    Data_frame_finale[i]=Data_frame_finale[i].astype(str).str.strip().str.title()